templates:
  - build/sources.template
  - build/objects.template
  - build/Makefile.template
  - build/source/subdir.template
  - build/includes/STM32F4xx_StdPeriph_Driver/src/subdir.template
  - scripts/arm_cortex_m4_512.template
  - includes/CMSIS/arm_common_tables.template
  - includes/CMSIS/arm_math.template
  - includes/CMSIS/core_cm0.template
  - includes/CMSIS/core_cm3.template
  - includes/CMSIS/core_cm4.template
  - includes/CMSIS/core_cm4_simd.template
  - includes/CMSIS/core_cmFunc.template
  - includes/CMSIS/core_cmInstr.template
  - includes/STM32F4xx/stm32f4xx_conf.template
  - includes/STM32F4xx/stm32f4xx.template
  - includes/STM32F4xx/system_stm32f4xx.template
  - includes/STM32F4xx_StdPeriph_Driver/inc/misc.template
  - includes/STM32F4xx_StdPeriph_Driver/inc/stm32f4xx_adc.template
  - includes/STM32F4xx_StdPeriph_Driver/inc/stm32f4xx_can.template
  - includes/STM32F4xx_StdPeriph_Driver/inc/stm32f4xx_crc.template
  - includes/STM32F4xx_StdPeriph_Driver/inc/stm32f4xx_cryp.template
  - includes/STM32F4xx_StdPeriph_Driver/inc/stm32f4xx_dac.template
  - includes/STM32F4xx_StdPeriph_Driver/inc/stm32f4xx_dbgmcu.template
  - includes/STM32F4xx_StdPeriph_Driver/inc/stm32f4xx_dcmi.template
  - includes/STM32F4xx_StdPeriph_Driver/inc/stm32f4xx_dma.template
  - includes/STM32F4xx_StdPeriph_Driver/inc/stm32f4xx_exti.template
  - includes/STM32F4xx_StdPeriph_Driver/inc/stm32f4xx_flash.template
  - includes/STM32F4xx_StdPeriph_Driver/inc/stm32f4xx_fsmc.template
  - includes/STM32F4xx_StdPeriph_Driver/inc/stm32f4xx_gpio.template
  - includes/STM32F4xx_StdPeriph_Driver/inc/stm32f4xx_hash.template
  - includes/STM32F4xx_StdPeriph_Driver/inc/stm32f4xx_i2c.template
  - includes/STM32F4xx_StdPeriph_Driver/inc/stm32f4xx_iwdg.template
  - includes/STM32F4xx_StdPeriph_Driver/inc/stm32f4xx_pwr.template
  - includes/STM32F4xx_StdPeriph_Driver/inc/stm32f4xx_rcc.template
  - includes/STM32F4xx_StdPeriph_Driver/inc/stm32f4xx_rng.template
  - includes/STM32F4xx_StdPeriph_Driver/inc/stm32f4xx_rtc.template
  - includes/STM32F4xx_StdPeriph_Driver/inc/stm32f4xx_sdio.template
  - includes/STM32F4xx_StdPeriph_Driver/inc/stm32f4xx_spi.template
  - includes/STM32F4xx_StdPeriph_Driver/inc/stm32f4xx_syscfg.template
  - includes/STM32F4xx_StdPeriph_Driver/inc/stm32f4xx_tim.template
  - includes/STM32F4xx_StdPeriph_Driver/inc/stm32f4xx_usart.template
  - includes/STM32F4xx_StdPeriph_Driver/inc/stm32f4xx_wwdg.template
  - includes/STM32F4xx_StdPeriph_Driver/src/misc.template
  - includes/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_adc.template
  - includes/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_can.template
  - includes/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_crc.template
  - includes/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp_aes.template
  - includes/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp.template
  - includes/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp_des.template
  - includes/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp_tdes.template
  - includes/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dac.template
  - includes/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dbgmcu.template
  - includes/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dcmi.template
  - includes/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dma.template
  - includes/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_exti.template
  - includes/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_flash.template
  - includes/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_fsmc.template
  - includes/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_gpio.template
  - includes/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_hash.template
  - includes/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_hash_md5.template
  - includes/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_hash_sha1.template
  - includes/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_i2c.template
  - includes/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_iwdg.template
  - includes/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_pwr.template
  - includes/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rcc.template
  - includes/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rng.template
  - includes/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rtc.template
  - includes/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_sdio.template
  - includes/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_spi.template
  - includes/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_syscfg.template
  - includes/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_tim.template
  - includes/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_usart.template
  - includes/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_wwdg.template
  - source/tinynew.template
  - source/system_stm32f4xx.template
  - source/syscall.template
  - source/startup_stm32f4xx.template
  - source/main.template

modules:
  - build/sources.mk
  - build/objects.mk
  - build/Makefile
  - build/source/subdir.mk
  - build/includes/STM32F4xx_StdPeriph_Driver/src/subdir.mk
  - scripts/arm_cortex_m4_512.ld
  - includes/CMSIS/arm_common_tables.h
  - includes/CMSIS/arm_math.h
  - includes/CMSIS/core_cm0.h
  - includes/CMSIS/core_cm3.h
  - includes/CMSIS/core_cm4.h
  - includes/CMSIS/core_cm4_simd.h
  - includes/CMSIS/core_cmFunc.h
  - includes/CMSIS/core_cmInstr.h
  - includes/STM32F4xx/stm32f4xx_conf.h
  - includes/STM32F4xx/stm32f4xx.h
  - includes/STM32F4xx/system_stm32f4xx.h
  - includes/STM32F4xx_StdPeriph_Driver/inc/misc.h
  - includes/STM32F4xx_StdPeriph_Driver/inc/stm32f4xx_adc.h
  - includes/STM32F4xx_StdPeriph_Driver/inc/stm32f4xx_can.h
  - includes/STM32F4xx_StdPeriph_Driver/inc/stm32f4xx_crc.h
  - includes/STM32F4xx_StdPeriph_Driver/inc/stm32f4xx_cryp.h
  - includes/STM32F4xx_StdPeriph_Driver/inc/stm32f4xx_dac.h
  - includes/STM32F4xx_StdPeriph_Driver/inc/stm32f4xx_dbgmcu.h
  - includes/STM32F4xx_StdPeriph_Driver/inc/stm32f4xx_dcmi.h
  - includes/STM32F4xx_StdPeriph_Driver/inc/stm32f4xx_dma.h
  - includes/STM32F4xx_StdPeriph_Driver/inc/stm32f4xx_exti.h
  - includes/STM32F4xx_StdPeriph_Driver/inc/stm32f4xx_flash.h
  - includes/STM32F4xx_StdPeriph_Driver/inc/stm32f4xx_fsmc.h
  - includes/STM32F4xx_StdPeriph_Driver/inc/stm32f4xx_gpio.h
  - includes/STM32F4xx_StdPeriph_Driver/inc/stm32f4xx_hash.h
  - includes/STM32F4xx_StdPeriph_Driver/inc/stm32f4xx_i2c.h
  - includes/STM32F4xx_StdPeriph_Driver/inc/stm32f4xx_iwdg.h
  - includes/STM32F4xx_StdPeriph_Driver/inc/stm32f4xx_pwr.h
  - includes/STM32F4xx_StdPeriph_Driver/inc/stm32f4xx_rcc.h
  - includes/STM32F4xx_StdPeriph_Driver/inc/stm32f4xx_rng.h
  - includes/STM32F4xx_StdPeriph_Driver/inc/stm32f4xx_rtc.h
  - includes/STM32F4xx_StdPeriph_Driver/inc/stm32f4xx_sdio.h
  - includes/STM32F4xx_StdPeriph_Driver/inc/stm32f4xx_spi.h
  - includes/STM32F4xx_StdPeriph_Driver/inc/stm32f4xx_syscfg.h
  - includes/STM32F4xx_StdPeriph_Driver/inc/stm32f4xx_tim.h
  - includes/STM32F4xx_StdPeriph_Driver/inc/stm32f4xx_usart.h
  - includes/STM32F4xx_StdPeriph_Driver/inc/stm32f4xx_wwdg.h
  - includes/STM32F4xx_StdPeriph_Driver/src/misc.c
  - includes/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_adc.c
  - includes/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_can.c
  - includes/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_crc.c
  - includes/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp_aes.c
  - includes/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp.c
  - includes/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp_des.c
  - includes/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_cryp_tdes.c
  - includes/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dac.c
  - includes/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dbgmcu.c
  - includes/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dcmi.c
  - includes/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_dma.c
  - includes/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_exti.c
  - includes/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_flash.c
  - includes/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_fsmc.c
  - includes/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_gpio.c
  - includes/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_hash.c
  - includes/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_hash_md5.c
  - includes/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_hash_sha1.c
  - includes/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_i2c.c
  - includes/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_iwdg.c
  - includes/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_pwr.c
  - includes/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rcc.c
  - includes/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rng.c
  - includes/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_rtc.c
  - includes/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_sdio.c
  - includes/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_spi.c
  - includes/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_syscfg.c
  - includes/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_tim.c
  - includes/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_usart.c
  - includes/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_wwdg.c
  - source/tinynew.cpp
  - source/system_stm32f4xx.c
  - source/syscall.c
  - source/startup_stm32f4xx.S
  - source/main.cpp
